class Solution:
    def countGoodIntegers(self, n: int, k: int) -> int:
        from collections import defaultdict
        from math import comb
        
        # We'll use dynamic programming or combinatorial counting for the multisets and then check for divisibility.
        # But note: n is up to 10, so we can use recursion/backtracking to generate all multisets (frequency distributions) for n digits (digits 0-9) that satisfy the palindrome condition (at most one odd frequency) and then check for the existence of a palindrome divisible by k.
        # However, we need to count the numbers (each distinct n-digit number) that have a multiset that can form a k-palindromic integer.

        # Alternatively, we can iterate over all n-digit numbers (from 10^(n-1) to 10^n - 1) and check the condition. But n is up to 10, so there are 10^n numbers, which is 10 billion, which is too many.

        # We need a smarter way.

        # Let's reframe: We are to count n-digit numbers (without leading zeros) such that the multiset of digits can form a palindrome and there exists a palindrome (from that multiset) divisible by k.

        # Step 1: Determine the set of multisets (frequency distributions) that can form a palindrome (i.e., at most one digit has odd frequency) and that have exactly n digits.

        # Step 2: For each such multiset, check if there exists a palindrome (using the multiset) that is divisible by k.

        # Step 3: For each multiset that satisfies step 2, count the number of n-digit numbers (without leading zeros) that have that multiset.

        # But note: the same multiset can be used by multiple numbers. The count of numbers for a multiset is the multinomial coefficient (n! / (product(factorial(count_i) for each digit i)) multiplied by the number of ways to assign the digits to positions, but then we must subtract those with leading zeros.

        # However, the problem is that the condition for being good is about the multiset, so we can group numbers by their multiset.

        # But the total number of multisets for n digits (with digits 0-9) is C(n+9, 9) which is manageable for n=10 (about 92378 multisets). But then we need to check for each multiset if it can form a palindrome (which is a condition on the frequencies) and then check if there exists a palindrome (from that multiset) divisible by k.

        # But then, how to check condition 2 for a multiset? We need to form a palindrome from the multiset and check divisibility by k. But the palindrome is determined by the first ceil(n/2) digits. The number of distinct palindromes from a multiset is the multinomial coefficient for the first half, but then we have to consider the entire number.

        # Alternatively, we can use dynamic programming to generate all palindromic numbers (with n digits) that are divisible by k and then check if the multiset of digits of that palindrome is the same as the multiset of the number we are counting? But that doesn't directly help.

        # Another idea: Instead of iterating over multisets, iterate over all palindromic numbers with n digits (without leading zeros) that are divisible by k. Then, for each such palindrome, count the number of n-digit numbers (without leading zeros) that have the same multiset as the palindrome. But then, we must avoid double-counting: if two different palindromic numbers (from the same multiset) are divisible by k, then the multiset is counted once. But actually, we are counting the numbers (each distinct n-digit number) that have a multiset that can form at least one k-palindromic integer. So, if a multiset can form multiple palindromic numbers, and at least one is divisible by k, then all numbers with that multiset are good.

        # So, we can do:

        # 1. Generate all palindromic numbers with n digits (without leading zeros) that are divisible by k. But note: the palindrome must be formed from the multiset of the number, but the number itself is not necessarily the palindrome. However, the condition is that the multiset can form a palindrome (any one) that is divisible by k.

        # 2. Then, for each such palindrome (each distinct multiset that can form a k-palindromic integer), count the number of n-digit numbers (without leading zeros) that have that multiset.

        # But note: the same multiset might be generated by multiple palindromic numbers.